[package]
name = "demo-app-cli"
description = "Command-line client: HTTP client, commands and output"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
